imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        only_exceptions: false

# Twig Configuration
twig:
    debug:            %kernel.debug%

# app/config/config.yml
services:
    twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }

web_profiler:
    toolbar: true
    intercept_redirects: true