outlandish_site:
    resource: "@OutlandishAcadOowpBundle/Resources/config/routing.yml"
    prefix: /

routemaster:
    resource: "@OutlandishRoutemasterBundle/Resources/config/routing.yml"
    prefix: /